Repository drs1951/CSC510_Group31, pull requests merged in 2023-10, with the labels that each got.

#18 Singup/Login/Menu/Inventory Form Validation Implemented
  package-lock.json
  package.json
  src/actions/actionTypes.js
  src/actions/auth.js
  src/actions/job.js
  src/components/App.js
  src/components/Goal.js
  src/components/Job.js
  src/components/Job1.js
  src/components/Login.js
  src/components/Menu.js
  src/components/Signup.js
  src/index.css
  src/reducers/auth.js
Labels: bug, enhancement

#20 Solved User Profile Picture not showing issue
  src/components/Navbar.js
  src/components/Settings.js
Labels: bug

#23 Notification Improvement
  package-lock.json
  package.json
  src/actions/auth.js
  src/components/App.js
  src/components/Card.css
  src/components/Goal.js
  src/components/History.js
  src/components/Job.js
  src/components/Job1.js
  src/components/Navbar.js
  src/components/Notification.js
  src/index.css
Labels: bug, enhancement

#28 Update README.md
  README.md
Labels: documentation

#31 Update README.md
  README.md
Labels: documentation

#30 Front test
  package-lock.json
  package.json
  src/components/Application.js
  src/components/UserApplication.js
  src/components/index.js
  src/tests/Application.test.js
  src/tests/Job1.test.js
  src/tests/Job2.test.js
  src/tests/Menu.test.js
  src/tests/Notification.test.js
  src/tests/Order.test.js
  src/tests/Update.test.js
  src/tests/UserApplication.test.js
  src/tests/__snapshots__/App.test.js.snap
  src/tests/__snapshots__/Goal.test.js.snap
  src/tests/__snapshots__/History.test.js.snap
  src/tests/__snapshots__/Home.test.js.snap
  src/tests/__snapshots__/Job.test.js.snap
  src/tests/__snapshots__/Job1.test.js.snap
  src/tests/__snapshots__/Job2.test.js.snap
  src/tests/__snapshots__/Login.test.js.snap
  src/tests/__snapshots__/Menu.test.js.snap
  src/tests/__snapshots__/Navbar.test.js.snap
  src/tests/__snapshots__/Notification.test.js.snap
  src/tests/__snapshots__/Order.test.js.snap
  src/tests/__snapshots__/Page404.test.js.snap
  src/tests/__snapshots__/Settings.test.js.snap
  src/tests/__snapshots__/Signup.test.js.snap
  src/tests/__snapshots__/Update.test.js.snap
Labels: enhancement

#32 Backend test guide added
  README.md
Labels: documentation

#33 Frontend Documentation
  docs/frontend_testing.md
  docs/test/app_test.md
  docs/test/goal_test.md
  docs/test/history_test.md
  docs/test/home_test.md
  docs/test/job2_test.md
  docs/test/job_test.md
  docs/test/login_test.md
  docs/test/menu_test.md
  docs/test/navbar_test.md
  docs/test/notifications_test.md
  docs/test/order_test.md
  docs/test/setting_test.md
  docs/test/signup_test.md
  docs/test/update_test.md
Labels: documentation

#35 Update README.md
  README.md
Labels: documentation
